version: 1
disable_existing_loggers: False
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: basic
  file:
    class: logging.handlers.RotatingFileHandler
    filename: log/t.log
    maxBytes: 10485760 # 10M
    backupCount: 50
    encoding: utf-8
    formatter: basic
formatters:
  basic:
    format: "%(levelname)-8s [%(asctime)s] [pid:%(process)s] [filename:%(filename)s] [fun:%(funcName)s] [lineno:%(lineno)d] [%(name)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
loggers:
  verbose:
    handlers: [console]
    level: INFO
    propagete: False # 日志传播
  audit:
    handlers: [file]
    level: DEBUG
    propagete: False
  root:
    handlers: [console]
    level: INFO

# http://python.usyiyi.cn/translate/python_352/library/logging.config.html
